### ISSUE TITLE
[9.0] `sc_*_allowed` fields aren't computed when creating a new record from UI 

### ISSUE THREAD

**Issue by zakiuu** [acsone/scobidoo#10]
**The issue**: When trying to create a new record from the UI of a model that uses statechart, allowed actions on the initial state aren't allowed until the record is saved.
**Technically speaking**: `sc_*_allowed` fields aren't computed when creating a new record from UI until that record is saved.

**Expected behaviour**: All the actions allowed in the initial state should be allowed to be used, from the UI when the user trying to create a new record.

**Comment by sbidoul** [comment]
Strangely enough, this test pass: https://github.com/acsone/scobidoo/commit/0c44b118023f677e00ddc91a052a65eaf0e6846d

**Comment by sbidoul** [comment]
@zakiuu I think I nailed it.

**Comment by zakiuu** [comment]
![200w_s](https://user-images.githubusercontent.com/222333/36558675-0e0d130a-180c-11e8-902b-4252e540cefc.gif)
