### ISSUE TITLE
Eventless transitions from initial state do not trigger

### ISSUE THREAD

**Issue by sbidoul** [acsone/scobidoo#19]
When there are eventless transitions from the **initial state** they do not trigger automatically.

Eventless transitions work normally from other states.

**Comment by AlexandreDecan** [comment]
Is this a bug in sismic? If yes, could you report it with a reproducible example so I can try to address it? Thanks

**Comment by sbidoul** [comment]
@AlexandreDecan I've not investigated yet. Probably not due to Sismic. If it is I'll provide with a test case for sure.
