### ISSUE TITLE
Any brief documentation will help alot, the demo is not same as it on video?

### ISSUE THREAD

**Issue by bunhin** [acsone/scobidoo#22]
Hi,
very interesting project
It is not an issue actually, but a humble request for a brief documentation to implement this statechart, it may help alot,
I have follow (watch) the video as well as the slide, it is quite different between the one showed in video and with the purchase_demo modules in this repo,  there are so many files in the models folder of purchase demo, while it looks like only need a statechart yml file in the video.
Thanks

**Comment by sbidoul** [comment]
I agree. Actually the demo module in this repo is misnamed, it's more a collection of exotic use cases for the sake of the test suite.

**Comment by idadzie** [comment]
@sbidoul Is there any ETA on the documentation? :smile:
