### ISSUE TITLE
Can't insert a accentuated character in a statechart YML file?

### ISSUE THREAD

**Issue by Laurent-Corron** [acsone/scobidoo#24]
**The issue:**
Can't use accentuated characters in a YML file.

**Technically speaking:** 
 when placing a line such as in a 'action' like so:
`o._sc_example("Activité")`
I will get an error: `StatechartError: YAML validation failed`
where as if i change it to:
`o._sc_example("Activit")`
everything will work fine.

**Expected behaviour:**
To be able to use accentuated characters in a YML file.

Am I missing a parametre here?
Thank you for any help

**Comment by sbidoul** [comment]
Is it python 2 or 3?

**Comment by Laurent-Corron** [comment]
Python 2 with odoo10

**Comment by sbidoul** [comment]
Hm, does not seem trivial to fix. Can you work around it, waiting for python 3?

**Comment by Laurent-Corron** [comment]
Ok I will work around it, I was just checking if there was an easy fix :wink:.
